name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and package with Maven
        run: mvn --batch-mode clean package

      - name: List target contents
        run: |
          echo "Checking for JAR in ./target"
          ls -lh target || echo "target directory not found"

      - name: Copy JAR to staging directory
        run: |
          mkdir -p staging
          cp target/*.jar staging/ || echo "No JAR file found in target/"

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
